---
# K8s manifest for nhs scrapy
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nhs-scrapy
  labels:
    app: nhs
    tier: scrapy
spec:
  template:
    spec:
      initContainers:
        - name: create-nhs-topic
          image: solsson/kafka:0.11.0.0
          command:
            - 'sh'
            - '-c'
            - |
              exec 2>&1
              COUNTER=0
              while [  $COUNTER -lt 20 ]; do
                brokers=$(echo dump | nc solr-zookeeper-2.solr-zookeeper-headless 2181 | grep brokers)
                if [ $? -eq 1 ] || [ -z $brokers ]; then
                  echo "Kafka is NOT running , waiting. $COUNTER attempts...";
                  COUNTER=`expr $COUNTER + 1`;
                  sleep 6;
                else
                  echo "Kafka is running ";
                  break;
                fi                
              done;
              if [ $COUNTER -eq 20 ]; then
                echo "Kafka not running. Giving up .........";
                exit 1;
              else
                echo "Creating THE topic!!!!"
                bin/kafka-topics.sh --create --if-not-exists --zookeeper solr-zookeeper-0.solr-zookeeper-headless:2181,solr-zookeeper-1.solr-zookeeper-headless:2181,solr-zookeeper-2.solr-zookeeper-headless:2181  --replication-factor 1 --partitions 1 --topic scrapypipe;
              fi

      containers:
      - name: nhs-scrapy
        image: pjmd-ubuntu.com/scrapy-nhs:v0.0.6
        env:
          - name: KAFKA_HOST
            value: 'kafka-svc'
          - name: BULK_SEND
            value: 'yes'
          - name: FILES_STORE
            value: /app/nhs_test_files
        command: ["/app/docker_send_test_files.sh"]

      restartPolicy: Never
  backoffLimit: 4
