---
# K8s manifest for nhs scrapy
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nhs-scrapy
  labels:
    app: nhs
    tier: scrapy
spec:
  template:
    spec:
      initContainers:
        - name: create-nhs-topic
          image: solsson/kafka:0.11.0.0
          command:
            - 'sh'
            - '-c'
            - "bin/kafka-topics.sh --create --if-not-exists --zookeeper solr-zookeeper-0.solr-zookeeper-headless:2181,solr-zookeeper-1.solr-zookeeper-headless:2181,solr-zookeeper-2.solr-zookeeper-headless:2181  --replication-factor 1 --partitions 1 --topic scrapypipe"

      containers:
      - name: nhs-scrapy
        image: pjmd-ubuntu.com/scrapy-nhs:v0.0.5
        env:
          - name: KAFKA_HOST
            value: 'kafka-svc'
          - name: BULK_SEND
            value: 'yes'
          - name: FILES_STORE
            value: /app/nhs_test_files
        command: ["/app/docker_send_test_files.sh"]

      restartPolicy: Never
  backoffLimit: 4
